import type { Metadata } from "next";
import "./globals.css";
import NavBar from "@/components/nav/NavBar";

export const metadata: Metadata = {
  title: "NextMatch",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <NavBar />
        <main className="container mx-auto mt-24">
          {children}
        </main>
      </body>
    </html>
  );
}
